#!/bin/bash
interface=""
while [ -z $interface ]
do
     ip -o link \
     | grep -o -E '^[0-9]+:\s+([a-zA-Z0-9]+):'\
     | awk -F ': ' '{print substr($2, 1, length($2)-1)}'\
     | grep -v "lo"
     printf "Type in the interface you wish to change: "
     read interface
     if ip link show "$interface" &>/dev/null; then
	     if sudo ip addr add 192.168.100.10/24 dev $interface &>/dev/null;\
	     then 
		     echo "Interface modified."
             else
		     echo "Interface has already been modified."
	     fi
     else
     	     echo "$interface does not exist, try again."
             interface=""

     fi
done


