# Let NetworkManager manage all devices on this system
network:
  ethernets:
    ens33:
      addresses:
        - 192.168.100.10/24
      routes: 
        - to: default
          via: 192.168.127.2
      nameservers:
        search: [ddp.is]
        addresses: [8.8.8.8, 4.4.4.4]

  version: 2
  renderer: NetworkManager

